name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Superlint
        uses: github/super-linter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@master

      - name: Install asdf
        uses: asdf-vm/actions/install@master

      - run: npm i

      - name: Build (make)
        run: make build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - name: Build (make)
        run: make build

      - name: Create new release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
